// <auto-generated />
using System;
using BakeryApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BakeryAPI.Migrations
{
    [DbContext(typeof(BakeryDbContext))]
    [Migration("20260911122348_userandresetpasswordReationship")]
    partial class userandresetpasswordReationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BakeryApi.Domain.Entities.ResetPassword", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("created_at")
                        .HasColumnType("date");

                    b.Property<DateOnly>("expired_at")
                        .HasColumnType("date");

                    b.Property<bool>("is_used")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("last_reset_timeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("rate_limit")
                        .HasColumnType("integer");

                    b.Property<int>("resetPasswordid")
                        .HasColumnType("integer");

                    b.Property<string>("token_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.Property<int?>("user_id1")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("resetPasswordid");

                    b.HasIndex("user_id1");

                    b.ToTable("ResetPassword");
                });

            modelBuilder.Entity("BakeryApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("BakeryApi.Domain.Entities.ResetPassword", b =>
                {
                    b.HasOne("BakeryApi.Domain.Entities.ResetPassword", "resetPassword")
                        .WithMany()
                        .HasForeignKey("resetPasswordid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApi.Domain.Entities.User", null)
                        .WithMany("resetPasswords")
                        .HasForeignKey("user_id1");

                    b.Navigation("resetPassword");
                });

            modelBuilder.Entity("BakeryApi.Domain.Entities.User", b =>
                {
                    b.Navigation("resetPasswords");
                });
#pragma warning restore 612, 618
        }
    }
}
